web:
  restart: always
  image: daocloud.io/yichentec/chinese_edu:latest
  expose:
    - "8000"
  volumes:
    - /usr/src/app
    - /usr/src/app/CEdu/static
  working_dir: /usr/src/app
  command: /usr/local/bin/gunicorn edu.wsgi:application -w 2 -b :8000
  
nginx:
  restart: always
  image: daocloud.io/library/nginx:latest
  ports:
    - "80:80"
  volumes:
    - /sites-enabled/:/etc/nginx/sites-enabled
  volumes_from:
    - web
  links:
    - web:web